// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ-QFvsUtqnxsehdZBymQc2HAaw6_BxpI',
    appId: '1:96951249626:web:b22558ffe2c7d56d0b93e3',
    messagingSenderId: '96951249626',
    projectId: 'chatapp-6d382',
    authDomain: 'chatapp-6d382.firebaseapp.com',
    storageBucket: 'chatapp-6d382.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNAB22mQ-dzt-WmoubXzIqwb-XPhtXPkc',
    appId: '1:96951249626:android:1a5171131d89397e0b93e3',
    messagingSenderId: '96951249626',
    projectId: 'chatapp-6d382',
    storageBucket: 'chatapp-6d382.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC380F26kFhDAsA7g0bchQKyLMNTX55ffU',
    appId: '1:96951249626:ios:cf67f39aa6492eaf0b93e3',
    messagingSenderId: '96951249626',
    projectId: 'chatapp-6d382',
    storageBucket: 'chatapp-6d382.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC380F26kFhDAsA7g0bchQKyLMNTX55ffU',
    appId: '1:96951249626:ios:a2de0a3f50e358fe0b93e3',
    messagingSenderId: '96951249626',
    projectId: 'chatapp-6d382',
    storageBucket: 'chatapp-6d382.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
